gate_detection:
  ros__parameters:
    # Pool depth used for removing floor points
    pool_depth: -2.1336
    # Gate size used to verify clusters
    gate_size: 3.0
    gate_size_tolerance: 0.3
    remove_statistical_outlier_nb_neighbors: 30
    remove_statistical_outlier_std_ratio: 3.0
    dbscan_eps: 0.3
    dbscan_min_points: 40
    remove_floor_tolerance: 0.4
    side_pole_height_min: 1.3
    side_pole_heiight_max: 1.7
    tx_override: -1.0