/**:
    ros__parameters:
      video_device: "/dev/video4"
      frame_id: "camera_5"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      camera_name: "camera_low_light_angled"
      camera_info_url: "package://pontus_sensors/config/front_right_camera_calibration.yaml"
