/**:
    ros__parameters:
      video_device: "/dev/video0"
      frame_id: "camera_front"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      # av_device_format: "M-JPEG"
      camera_name: "camera_front"
      image_height: 480
      image_width: 640
      fps: 30
      camera_info_url: "package://pontus_sensors/config/front_left_camera_calibration.yaml"
