# Sensors

# Camera Forward Left
- ros_topic_name: "/pontus/camera_front/image_raw"
  gz_topic_name: "/pontus/camera_front/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/pontus/camera_front/camera_info"
  gz_topic_name: "/pontus/camera_front/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/pontus/camera_3/camera_info"
  gz_topic_name: "/pontus/camera_3/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Camera Forward Right
- ros_topic_name: "/pontus/camera_3/image_raw"
  gz_topic_name: "/pontus/camera_3/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Camera Side Left
- ros_topic_name: "/pontus/camera_4/image_raw"
  gz_topic_name: "/pontus/camera_4/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Camera Side Right
- ros_topic_name: "/pontus/camera_5/image_raw"
  gz_topic_name: "/pontus/camera_5/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Camera Downward
- ros_topic_name: "/pontus/camera_1/image_raw"
  gz_topic_name: "/pontus/camera_1/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Sonar Forward
# - ros_topic_name: "/pontus/sonar_0"
#   gz_topic_name: "/pontus/sonar_0"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS
- ros_topic_name: "/pontus/sonar_0/sim"
  gz_topic_name: "/pontus/sonar_0/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS


# Sonar Top 360
# - ros_topic_name: "/pontus/sonar_1"
#   gz_topic_name: "/pontus/sonar_1"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/pontus/imu_0"
  gz_topic_name: "/pontus/imu_0"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Pressure
- ros_topic_name: "/pontus/pressure_0"
  gz_topic_name: "/pontus/pressure_0"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS


# Thrusters

# Thruster 0
- ros_topic_name: "/pontus/thruster_0/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_0/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 1
- ros_topic_name: "/pontus/thruster_1/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_1/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 2
- ros_topic_name: "/pontus/thruster_2/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_2/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 3
- ros_topic_name: "/pontus/thruster_3/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_3/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 4
- ros_topic_name: "/pontus/thruster_4/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_4/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 5
- ros_topic_name: "/pontus/thruster_5/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_5/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 6
- ros_topic_name: "/pontus/thruster_6/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_6/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 7
- ros_topic_name: "/pontus/thruster_7/cmd_thrust"
  gz_topic_name: "/model/pontus/joint/prop_joint_7/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# GZ Sim Parameters

# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
